name: EKS Cluster Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  CLUSTER_NAME: your-cluster-name  # or set this in GitHub secrets/variables

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          # First delete nodegroups explicitly
          NODEGROUPS=$(aws eks list-nodegroups \
            --cluster-name ${{ env.CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --query "nodegroups" \
            --output text)
          
          if [ -n "$NODEGROUPS" ]; then
            echo "Found nodegroups: $NODEGROUPS"
            for NODEGROUP in $NODEGROUPS; do
              echo "Deleting nodegroup $NODEGROUP..."
              aws eks delete-nodegroup \
                --cluster-name ${{ env.CLUSTER_NAME }} \
                --nodegroup-name $NODEGROUP \
                --region ${{ secrets.AWS_REGION }} || true
            done
            
            echo "Waiting for nodegroups to delete..."
            for NODEGROUP in $NODEGROUPS; do
              aws eks wait nodegroup-deleted \
                --cluster-name ${{ env.CLUSTER_NAME }} \
                --nodegroup-name $NODEGROUP \
                --region ${{ secrets.AWS_REGION }} || true
            done
          else
            echo "No nodegroups found"
          fi
          
          # Now run terraform destroy
          terraform destroy -auto-approve -input=false
          
          # Final verification
          if aws eks describe-cluster \
            --name ${{ env.CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} &>/dev/null; then
            echo "Cluster still exists!"
            exit 1
          else
            echo "Cluster successfully destroyed"
          fi
